"""first migration

Revision ID: 5a6fa4bc8e4d
Revises: 66a390c855f5
Create Date: 2023-04-13 15:31:25.280527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a6fa4bc8e4d'
down_revision = '66a390c855f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
